### ISSUE TITLE
Where is the importable solution?

### ISSUE THREAD

**Issue by james-reinhardt** [mkcgphy/Azure-Maps-Get-Search-Address-TypeAhead#1]
I'm sorry if I'm missing something, but is there a zip solution for importing into a CDS environment? Thanks in advance.

**Comment by mkcgphy** [comment]
Hi James,

I have added zip file for download. Do let me know if you still face any issue. Do note that key is required for this code to work. 

Thanks

**Comment by james-reinhardt** [comment]
Thank you for doing that. I'm a bit confused on the instructions, do I need to create a custom action for the control to use, or is there one in the project? I have the Azure key, but am not sure what needs to be configured for the action.
If this requires coding, I'll pass it on to one of my developers to look at the additional needed pieces. Thanks a bunch.

**Comment by mkcgphy** [comment]
Yes , the idea was not to expose the API Key over each call and keep it configurable for each environment. So we went with action approach. If you would like to customize the code feel free to uncomment the part which says use it with keys to make direct calls using JS . Please make your model according to what is returned in calls. I think that would be part of development team if you are into business. I would recommend using the actual azure sample blog which explains in detail as to how to use it . 

https://azuremapscodesamples.azurewebsites.net/?sample=Fill%20Address%20Form%20with%20Autosuggest

Thanks

**Comment by james-reinhardt** [comment]
Thank you so much for all of the detail. We were able to get it working as is.
