### ISSUE TITLE
Solution Export/Import failing with MJ.AddressTypeAhead

### ISSUE THREAD

**Issue by BC-Kevin** [mkcgphy/Azure-Maps-Get-Search-Address-TypeAhead#20]
Hello -
Intending to export solution out of one environment and into another. Receiving this message. Solution "{ExportedSolutionName}" failed to import: Import Solution Failed: CustomControls with Name MJ.AddressTypeAhead Import Solution Failed with following error: Publisher prefix mj for this control MJ.AddressTypeAhead does not match the prefix {xyz} for the solution with Id {solution Id}.

Attempted to follow recommendations from this post and change the Address solutions Publisher from mj to {xyz} and re-export.  This did not result in success.  https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Model-Driven-App-Custom-Component-import-issue-with-solution/td-p/649775

Is there any changes to the implementation of this type ahead solution that would help resolve this?

**Comment by mkcgphy** [comment]
Hello,

Please make sure you are following the steps given at the end of this url :
https://rajeevpentyala.com/2022/07/01/pcf-component-import-error-publisher-prefix-for-this-control-does-not-match-the-prefix-for-the-solution/

Thanks

**Comment by BC-Kevin** [comment]
Thank you for the reference to this article!  I have inherited this scenario so I'm trying to figure out how to fix this.  I can change the prefix from the mj on the publisher however I cannot change the prefix on the control.  What I was doing is exporting the managed Address solution from the source environment and importing it into the target.  But maybe I need to publish the control from scratch to the target environment instead?  Is there a way to change the prefix of the control in the source environment?

**Comment by mkcgphy** [comment]
Hello again,

Did you follow the last step 

![image](https://user-images.githubusercontent.com/23548639/199315310-498bde51-a138-4f52-90d3-2b9524512c2d.png)


While creating the solution use + New Publisher option which you can do . 

Thanks

**Comment by BC-Kevin** [comment]
No luck.  Steps:
1. Removed the MJ Address solution from target environment.
2. Updated existing ManishJain publisher's prefix to be BCWS
3. Started Import of MJ Address solution to target.
4. Receive error stating that the prefix is not BCWS.
5. Crack open the downloaded MJ Address solution and change all references to a lower case mj to bcws.
6. Attempt to import and still get the same message.
7. Deleted publisher and added it as new
8. repeated attempt to import and was presented with same error.
I have no idea how it seems that the prefix is 'mj'.
![image](https://user-images.githubusercontent.com/71780045/199325100-cda0dc56-9ee9-45de-8e96-5e50f2a1c0d8.png)

**Comment by BC-Kevin** [comment]
Okay, I was able to get it into a clean target environment.  (I missed one 'mj' substitution in my modified solution).  I cannot get it into the first target environment because it says the control was created by another publisher.  I'll try to start over and see if I get farther.  Thanks for the help.
